CREATE DATABASE IF NOT EXISTS AdocaoDePets;
USE AdocaoDePets;

CREATE TABLE IF NOT EXISTS Pets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    especie VARCHAR(10) NOT NULL,
    idade INT NOT NULL,
    descricao TEXT,
    status ENUM('Disponível', 'Adotado') DEFAULT 'Disponível'
);

CREATE TABLE IF NOT EXISTS Adotantes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    telefone VARCHAR(15), 
    endereco TEXT
);

CREATE TABLE IF NOT EXISTS Adocoes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pet_id INT NOT NULL,
    adotante_id INT NOT NULL,
    data_adocao DATE NOT NULL,
    FOREIGN KEY (pet_id) REFERENCES Pets(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (adotante_id) REFERENCES Adotantes(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE
=INNODB;